#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-File-Type
Version  : 0.22
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/P/PM/PMISON/File-Type-0.22.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PM/PMISON/File-Type-0.22.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libf/libfile-type-perl/libfile-type-perl_0.22-3.debian.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-File-Type-license
Requires: perl-File-Type-man

%description
NAME
File::Type - determine file type using magic
INSTALLING
Install using the standard Module::Build method:

%package license
Summary: license components for the perl-File-Type package.
Group: Default

%description license
license components for the perl-File-Type package.


%package man
Summary: man components for the perl-File-Type package.
Group: Default

%description man
man components for the perl-File-Type package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n File-Type-0.22
mkdir -p %{_topdir}/BUILD/File-Type-0.22/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/File-Type-0.22/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-File-Type
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-File-Type/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/File/Type.pm
/usr/lib/perl5/site_perl/5.26.1/File/Type/Builder.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-File-Type/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/File::Type.3
/usr/share/man/man3/File::Type::Builder.3
